### ISSUE TITLE
Link outs to ENSEMBL gene IDs on PanTree pages

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/paint#1]
Hi,

I had a WB user ask about supporting evidence for a PAINT annotation.

I directed them to the corresponding PanTree node page:
http://pantree.org/node/annotationNode.jsp?id=PTN000433338
but it looks like none of the ENSEMBL IDs link out to Ensembl gene pages.

Can links be added to the Ensembl gene pages from the PTN pages?

Once on the Ensembl gene pages, it takes a bit of surfing around to find the associated GO annotations (I got there through the Protein Families link).

We use the PTN entries in the With/From column for supporting information; is there a better place to direct users?

Thanks,
--Kimberly

**Comment by selewis** [comment]
I know this is a PANTREE question (so more for Huaiyu), but what I've found works for PAINT is linking the ENSEMBL genes using this template: http://www.ensembl.org/Danio_rerio/Gene/Summary?g=ENSDARG00000052289

What makes these URL templates a nuisance is that it needs to include the genus_species as a part of the URL so they're not generic.

**Comment by selewis** [comment]
Huaiyu 

Send me you github user name so that I can assign this to you.

**Comment by cmungall** [comment]
@huaiyumi

**Comment by huaiyumi** [comment]
We will take a look and fix the problem.
