### ISSUE TITLE
PAINT annotations are being generated for things with taxon restrictions

### ISSUE THREAD

**Issue by ValWood** [geneontology/paint#10]
See
https://github.com/geneontology/go-annotation/issues/1320

**Comment by selewis** [comment]
I believe this has been fixed. Entirely new approach to taxon checking now that uses the built in relationships properly. It is based on 'loss', as long as any descendant can have the function it is allowed, but it also then indicates a 'loss' at the appropriate phylogenetic clade by recursing down the phlyogeny.
