### ISSUE TITLE
PAINT file contents.

### ISSUE THREAD

**Issue by monicacecilia** [geneontology/paint#11]
@selewis @huaiyumi 
Valerie Wood @valwood reported this issue back in 2015-04-09  to the GO-Help Desk and it seems to have been buried in JIRA. It was brought up again two weeks ago and it appears the issue still needs to be addressed. http://jira.geneontology.org/browse/GO-799
I will post comments from each person separately. 

## Initial issue from @valwood : 
I'm not sure this is a directly a PAINT issue, but I noticed some anomolies in the PAINT file and I don't know where they would originate.
1. There are some PomBase entries with a "pi" gene name in column2 (Db object ID).
For example
5 pi006
5 pi013
4 pi021
6 pi026
2 pi036
3 pi038
2 pi040
3 pi042
3 pi047
9 pi051
3 pi058
3 pi072
5 pi077
8 pi078
These are not official PomBase DB:object IDs.
All of the PomBase protein entries have a database object ID beginning SP*
2.
227 entries have GeneDB_Spombe (there shouldn't be any entries with GeneDB_Spombe in the GO database, perhaps we just need to get rid of these. In addition some of these entries have uniprot IDs in column3 but I guess this problem will disappear when this is resolved ?)

## Response from @selewis:
So PANTHER previously was delivering two separate lines:
'SCHPO|PomBase=pi072|UniProtKB=O13663' '' 'GPI ethanolamine phosphate transferase 3' 'Schizosaccharomyces pombe' 'PomBase:SPBC27B12.06,PomBase:pi072' 'gpi13,gpi13' '' '' '' '' '' '' '' '' 'PTN000552957'
'SCHPO|PomBase=SPBC27B12.06|UniProtKB=O13663' '' 'GPI ethanolamine phosphate transferase 3' 'Schizosaccharomyces pombe' 'PomBase:SPBC27B12.06,PomBase:pi072' 'gpi13,gpi13' '' '' '' '' '' '' '' '' 'PTN001497162'
Basically same UniProt protein sequence, but two separate genes. (And PANTHER in turn gets its IDs from the GCRP (gene centric reference proteome, see Chris's Google doc on the various proteome sets).
In v10 of PANTHER this problem is gone, so once I can run touchup and there's a reload the problem should be gone.

## Tanya asked: 
Is this still an issue? From the PANTHER site, I see: Version 10.0 (release date May 15, 2015). If touchup has been run and a reload has occurred, the problem should be gone, according to Suzi's last comment.

## @valwood's latest response: issue still needs to be addressed 
Still an issue:
From here:
http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gene-associations/submission/paint/pre-submission/
pombase paint file still has annotations with GeneDB prefix, even though these IDs have not been used in the PomBase GAF for >5 years?
142 GeneDB_Spombe
7051 PomBase
column2 should only contain fission yeast systematic IDs but still has some old identifiers which are obsolete for about 10 yesasr (they did not correspond to single genes)
pi047
pi058
pi072
pi077
pi078
The following are synonyms of the following genes
pi013 is SPBC32H8.11
pi023 is SPBP22H7.08
pi026 is SPBP22H7.05c
pi035 is SPBC691.01
pi036 is SPBC17A3.10
pi038 is SPBC17A3.08
pi040 is SPBC17A3.06
pi042 is SPBC17A3.04c
pi044 is SPBC17A3.01c
I don’t really understand where these are coming from because the pombe protein sequences are fully represented in Swiss-prot 1:1

**Comment by ValWood** [comment]
Thanks Moni!

**Comment by monicacecilia** [comment]
@ValWood please see comment form @huaiyumi on 2015-12-09 (he responded in JIRA): 
These IDs are in reference proteome datasets that are used in PANTHER. I think I already sent the feedback to Uniprot about this problem.

@huaiyumi, may I kindly ask that you please share any feedback you get from UniProt? - if any.

**Comment by huaiyumi** [comment]
I added my comment there. Basically the data was provided by reference proteome. We sent our feedback to them already about this problem.

Thanks,

Huaiyu

**Comment by monicacecilia** [comment]
Ok. In that case, please close this issue whenever you think it is completed. 
THanks! :) 
cheers,

**Comment by huaiyumi** [comment]
I believe the issue was in the previous PANTHER (9.0). Reference proteome fixed it already, so it should not be in v10 anymore.

Thanks,

Huaiyu

**Comment by selewis** [comment]
Fixed.

**Comment by monicacecilia** [comment]
:dancer: :dancer: :dancer:
