### ISSUE TITLE
Annotations for high throughput papers on the exclusion list should not be shown in PAINT

### ISSUE THREAD

**Issue by pgaudet** [geneontology/paint#12]
Example: 
PTHR24387
20150604: Opisthokonta_PTN001348477 to nucleoplasm (GO:0005654)  using [UniProtKB:Q8WV37, UniProtKB:Q9Y2P7, UniProtKB:Q66K89, UniProtKB:O95625] - lacks supporting evidence

However in PAINT1.14 we still the reference supporting this (GO_REF:0000052). 

These references need to be removed from the display, or else we may accidentally reannotate them. 

Thanks, 
Pascale

**Comment by selewis** [comment]
They're gone now
