### ISSUE TITLE
pop-up to propagate qualifier comes up for terms that don't have the qualifier

### ISSUE THREAD

**Issue by krchristie** [geneontology/paint#13]
Hi,

I was doing PTHR12746.

I propagated the term "cytoplasm" to the root and got a popup asking if I wanted to propagate the "contributes_to" qualifier (from S. cerevisiae). However, the term that the qualifier is attached to is actually a different term "cytosolic large ribosomal subunit ; GO:0022625". It seems inappropriate that PAINT should be allowing me to propagate a qualifier to "cytoplasm" based on a much more specific term.

-Karen

**Comment by selewis** [comment]
Works in PAINT v2.12
