### ISSUE TITLE
PAINT should create a directory when we save

### ISSUE THREAD

**Issue by pgaudet** [geneontology/paint#16]
Hello, 

In PAINT-beta 15 we need to manually create a  folder and type its name (copy/paste does not work for me). It'd be less error prone if the files were directly saved in a directory. (Hopefully editing a family and re-saving it would not create additional directories! ). 

Thanks, Pascale

**Comment by selewis** [comment]
Closing because it's a duplicate. Same as https://github.com/geneontology/touchup/issues/43
