### ISSUE TITLE
order of GO aspects in Annotations tab

### ISSUE THREAD

**Issue by krchristie** [geneontology/paint#18]
It would be great if the order of GO aspects in the Annotations tab could match the order of annotations in the Protein Family tab, like it did in PAINT 1 versions (e.g. 1.14).

PAINT 2.0-beta14 has the three aspects in the Protein family tab listed as:
Molecular Function    Cellular Component    Biological Process

However, in the Annotations tab, BP is first, then MF, followed by CC. It would be great if BP was last like it used to be and matching the order in the other tab.

thanks,

-Karen

**Comment by selewis** [comment]
Fixed in PAINT 2.17

**Comment by krchristie** [comment]
Looks great. Thanks!
