### ISSUE TITLE
issues with propagations & with info for NOT annotations

### ISSUE THREAD

**Issue by krchristie** [geneontology/paint#19]
Hi,

I initially saw this for Paint2.0-beta14. I noticed that Pascale recently reported someting using 2.0-b15, so I just downloaded it and see the same issue in Paint2.0-beta15.

In the family PTHR13405, FB:FBgn0039004 has a NOT annotation to the BP term SMAD protein import into nucleus (GO:0007184). There are two problems related to this NOT annotation.

1. **NOT annotation to specific term blocking propagation of a more general term**
There is an annotation for YEAST NUP133 to "protein import into nucleus" (GO:0006606) that I propagated to the root node. However this term is not propagated to the Drosophila gene FB:FBgn0039004, even though the experimental annotation to the Drosophila gene is more specific than the term that is being propagated, and thus shouldn't block it.

2. **gene with NOT annotation being used to support propagation of positive annotation**
In all the annotation lines for the GO term "protein import into nucleus" (GO:0006606), the FB gene ID is included as well as the SGD ID, even though the annotation to the FB gene is a NOT annotation. Here is a sample line from a gaf (saved by 2.o-b15)

<pre>
MGI     MGI:2442620     Nup133          GO:0006606      PAINT_REF:13405 IBA     PANTHER:PTN000334066|SGD:S000001790|FB:FBgn0039004      P       nucleoporin 133 UniProtKB:Q8R0G9|PTN000334084|4832420O05Rik|mermaid     protein taxon:10090     20160427        GO_Central
</pre>
   
-Karen 

Note: I committed this family to SVN in November 2015 from Paint1.14. I have NOT updated SVN with new files saved from 2.0-b14.

**Comment by selewis** [comment]
Fixed in PAINT 2.17, please test

**Comment by krchristie** [comment]
Looks great. Thanks Suzi
