### ISSUE TITLE
Speed up of loading is essential

### ISSUE THREAD

**Issue by selewis** [geneontology/paint#2]
As an example PTHR23315 (1443 nodes) takes over an hour and still is stuck sorting terms out. Possibly it's crashed quietly, but I'm guessing it is traffic back-and-forth to GoLR. 
Need to work with Seth and Heiko on this

**Comment by hdietze** [comment]
One optimization is to replace the OWLGraphWrapper.getAncestors method. This method is known to be slow and very high memory requirements.
The stop gap is to use a similar approach to the amigo loader (ExpressionMaterializingReasoner)  until a full switch to Scigraph for such queries can be made.

**Comment by hdietze** [comment]
See example snippet: https://gist.github.com/hdietze/af03c672a1d18817b1b8
