### ISSUE TITLE
Investigate latency issues with PAINT connecting to services

### ISSUE THREAD

**Issue by cmungall** [geneontology/paint#24]
It appears that PAINT can take too long on startup.

Some possible causes:
- Connection to server not being closed, bringing down golr (cc @kltm )
- Iterative queries being used where a single query would suffice

Some steps towards diagnosis:
- A logger INFO call should be made for each Golr call. This way we can help better diagnose user issues.
- Code review Golr-client and PAINT code calling it

**Comment by cmungall** [comment]
See #1322 for some data points

**Comment by kltm** [comment]
@cmungall what tracker for #1322?

**Comment by cmungall** [comment]
oops, assumed it was the same, but obviously PAINT hasn't accumulated that many!

https://github.com/geneontology/go-annotation/issues/1322
