### ISSUE TITLE
PAINT annotations to ‘apoptotic process’ in plants

### ISSUE THREAD

**Issue by paolaroncaglia** [geneontology/paint#26]
Hello,

I just noticed some PAINT annotations to ‘apoptotic process’ for plant species (Viridiplantae). These are 165 IBAs, all with qualifier = NOT. May I please double-check this - I kind of remember that there was some issue in applying taxon constraints via PAINT but can’t recall if this was fixed. Apoptosis as such doesn’t occur in plants, and yes all those annotations say that some gene products are NOT involved in apoptosis in plants, but I’m assuming that the intent was to say that they are NOT involved in programmed cell death instead.

Thanks,
Paola

**Comment by selewis** [comment]
This will require someone to re-annotate the relevant families, which we cannot do unless we know the family ID (i.e. the PTHRnnnnn). To even begin to do this we need the Uniprot IDs for these proteins, but most direct is the PTHRnnnnn. IDs please of some sort.

**Comment by pgaudet** [comment]
I'm happy to be assigned this issue.
