### ISSUE TITLE
annotation in "Annotations" tab but not in "Annotation Matrix

### ISSUE THREAD

**Issue by krchristie** [geneontology/paint#3]
When I load PTHR12858 (either New or Open from my saved files) there is one annotation I need isn’t showing up in PAINT-b14 correctly. For S. cerevisiae TSR1, there are three experimental CC annotations (from SGD's Manual Annotations section) listed in the “Annotations” tab:
- cytoplasm
- nucleolus
- preribosome, small subunit precursor

However, in the “Annotation Matrix”, only two direct annotations show up, those for  “nucleolus” (1st column) and “cytoplasm” (3rd column). 

The "preribosome, small subunit precursor" annotation is IDA and is listed in SGD’s “Manually Curated” section, NOT in the HTP section. In contrast, the term "90S preribosome" which is listed only in SGD's "HTP" section does not show up in the "Annotations" tab:
http://www.yeastgenome.org/locus/S000002218/go 

I’ve tried loading this family a couple different times, and even after relaunching PAINT, I still get this problem and can’t propagate the "preribosome, small subunit precursor” because it isn’t in the annotation matrix.

**Comment by krchristie** [comment]
It looks to me like the experimental GOCN annotations from P2GO are _mostly_  being treated as already propagated, as if they were GOCN (aka GO_Central) annotations made by PAINT, though I have no suggestion for why a few of the P2GO GOCN annotations fail to show up in the annotation matrix.

- The ones that are showing in the Annotations Matrix are colored blue, e.g. already propagated. 

- In the “Annotations” tab, all of them are given the same icon as IBD annotations. So,  though 

I am also having this issue in PTHR23105, which is also blocking my ability to finish annotating the family. Specifically, the "90S preribosome" annotation by IDA for S. cerevisiae UTP30 is not present in the Annotation Matrix.

**Comment by selewis** [comment]
These are all showing up in both the annotations table and the matrix for TSR1: cytoplasm, nucleolus, nucleus, preribosome, small subunit precursor, and 90S preribosome in PAINTv2. 

Pascale is testing this now, and it should be release soon.
