### ISSUE TITLE
tree drawing issues (v2.25)

### ISSUE THREAD

**Issue by krchristie** [geneontology/paint#32]
HI Suzi,

It looks like v2.25 still has issues with squashing the tree view in some circumstances.

I had collapsed some nodes, which worked fine, but when I uncollapsed them, the tree view got squashed (treeViewAfterUncollapsingNode), compared to what it should be after I forced it to redraw by changing the scale (treeAfterRescaling).

-Karen

**Comment by selewis** [comment]
@krchristie - Yes indeed. I found the problem for this (have to do things in a certain order).
Should be in v2.27 which I hope will be out later today.
