### ISSUE TITLE
ability to submit tree issues other than pruning

### ISSUE THREAD

**Issue by krchristie** [geneontology/paint#4]
Hi,

As discussed at the August 18th PAINT meeting, both Pascale and I think it would be very useful to be able to submit comments and issues related to the tree structure where it is not necessary to prune. 

For example, sometiems we see a duplication node somewhere in the tree and it looks from the MSA that one or more subnodes under the duplication node does not belong with the rest of the tree. However, if that subnode(s) is experimentally characterized, it may be possible to annotate it from descendents completely separately from the main tree. In these situations, it is nice to go ahead and do annotations for the subnode (that should possibly be removed from the tree) as well as for the main portion of the family, rather than pruning the subnode from the tree and not annotating it at all.

It would be great if we had a way to officially designate within PAINT this sort of "tree issue" that merits inspection by the Panther team, so that it is not dependent on sending an email to Paul and Huaiyu.

-Karen

**Comment by pgaudet** [comment]
Hello, 

I would make this suggestion a little more specific by giving a few options - but right now I can only think of one option: 'node needs to be evaluated' (so that Panther folks can decide to remove/merge with a new family, etc). 

So upon right click on a node we'd have this extra option. 

Thanks, 
Pascale

**Comment by selewis** [comment]
Thanks Pascale, that was exactly the question I had: I don't think free
text would be all that useful to the PANTHER tree builders. What we've done
in other cases like this is to have 'canned' comments (that are
configurable) and then the user picks one from this list. I can easily
start with a list of one.

-S

**Comment by krchristie** [comment]
I agree that having specific options is valuable, but I would also like to be able to associate a comment with that option.

What about having a list of options and then an optional free text comment associated with it? I often have specific info about why the node needs to be evaluated, and sometimes about why I pruned a node. If I can't add that info about why I think the node  needs to be evaluated into PAINT itself, I'm probably going to end up email Huaiyu anyway.

thanks,
Karen

**Comment by krchristie** [comment]
Adding to my previous comment, sometimes I have info about where I think what family I think the node belongs in.

**Comment by selewis** [comment]
We can use the existing 'notes' region for any free text, and use the node
comment more as a way to categorize the type of problem in such a way that
it can be automatically detected programmatically. Once the tree/node is
recognized by such a script then whoever is fixing things can read the free
text.
