### ISSUE TITLE
notes persisting on loading new family is back

### ISSUE THREAD

**Issue by krchristie** [geneontology/paint#45]
Hi Suzi, 

This issue of notes persisting from the previous family when loading a new one seems to be back.

I was using v2.28.1. The note shown is from the previous family, PTHR38601, not the PTHR15431 family that has just been loaded.

![20161130-2 28 1-persistantnote](https://cloud.githubusercontent.com/assets/10533218/20775726/3fb4f39e-b711-11e6-8d2d-1c57819cfe2f.jpg)

thanks,

-Karen

**Comment by selewis** [comment]
Neither of these families appear to be in the svn repository so I can't test with exactly the same thing. In the mean time I tried loading existing+existing and existing+new and the problem is not appearing. Please provide an example I can use directly to work on this.

**Comment by krchristie** [comment]
PTHR38601 was already in SVN:
<pre>
bash-3.2$ svn log PTHR38601/PTHR38601.gaf
------------------------------------------------------------------------
r37420 | kchris | 2016-11-30 14:23:35 -0800 (Wed, 30 Nov 2016) | 1 line

not new annotations, examined but unannotated Panther family
------------------------------------------------------------------------
r37411 | kchris | 2016-11-30 11:04:54 -0800 (Wed, 30 Nov 2016) | 1 line

new PAINT annotations
------------------------------------------------------------------------
</pre>

PTHR15431 is not in SVN and I am not ready to commit yet, so I will send you a zipped copy of my directory.

Additional details required to duplicate this are that I opened the second family (PTHR15431) using "Open using server...". Possibly also relevant is the fact that PTHR15431 had info in its notes file.

**Comment by selewis** [comment]
Turns out this had nothing to do with the notes, it was the family PTHR15431 itself causing the issue. Turns out one of the PAINT annotations was a negation of a particular term (GO:42384) that is now obsolete. While PAINT was replacing/updating to the new term for the positive annotations, it was missing these.
