### ISSUE TITLE
GAFs output from PAINT need to conform to GAF spec 2.1

### ISSUE THREAD

**Issue by kltm** [geneontology/paint#49]
Currently, the rest of the pipeline is using GAF 2.1, whil PAINT is apparently still using 2.0.

The closure of this issue would be either

* the header is updated to 2.1 (in the case that the header is incorrect)
* the output GAF is updated to conform to GAF spec 2.1 and the header is updated to reflect this

This is either and enhancement or bug depending on which of the above it is.

**Comment by huaiyumi** [comment]
This is fixed.
