### ISSUE TITLE
PAINT GAF files coming from PANTHER need to include all 'with' information in the GAF

### ISSUE THREAD

**Issue by selewis** [geneontology/paint#50]
Without having the trees available we have no access to the original experimental information. Previously this info was included in the GAF files, but it seems to have disappeared. @huaiyumi when you generate the panther protein family GAFs from your database are you including this info? 

It's still needed and we're discussing the best way to convey it that would improve upon the comma (AND) separated withs that were used previously. 

For now we'd like to have the comma separated data available though.

**Comment by kltm** [comment]
Note possible relation to https://github.com/geneontology/go-site/issues/556

**Comment by cmungall** [comment]
I'm not sure exactly what the action is and who is responsible. I think this is a ticket just for @huiayu? It's best to use the assignee field for people who are doing the work (others can be `@`-mentioned).

Can you show an example of the relevant columns as they were before, and as they are now?

**Comment by huaiyumi** [comment]
The PTN ids are included in the 'with' column. I think the file format is exactly the same as the PAINT GAF files generated before. If more information is needed in that column, please let me know. We should put it in the document.

**Comment by selewis** [comment]
Based on our call today (March 29, 2018) @huaiyumi will begin adding these to the PAINT gaf files. So the "with" column will look something like this:
PANTHER:PTN001944787|RGD:727928|HGNC:32017
Note that this is a bandaid we're using purely as a convenience for packaging the experimental basis for the ancestral gene's annotation. It's one level removed. @cmungall and @kltm - at some point we should look at how to reflect the actual relationships in the GO-CAM format.

**Comment by selewis** [comment]
@huaiyumi - any chance you have an estimated arrival date for these? Would you coordinate with @kltm and @dougli1sqrd so that it doesn't just miss a pipeline run.

**Comment by huaiyumi** [comment]
As we discussed at the call about two weeks ago, the new PAINT GAF file will include leaf sequences that are used as evidence in the 'with' column.

**Comment by huaiyumi** [comment]
This is done in the most recent release.
