### ISSUE TITLE
Need a linkable URL formation for PTNs to PANTHERDB.org

### ISSUE THREAD

**Issue by selewis** [geneontology/paint#51]
Now that the with column is being included in the GO ribbon the PTN ancestral nodes are displayed. (See http://xenademo.berkeleybop.io:2992/gene/SGD:S000002976 and click on homeostasis for an example). As near as I can determine there is currently no means of using a PTN id to open the appropriate tree on the PANTHER site. We'd really like to link to PANTHER, but right now a link is impossible (including a silly Google search).

Help?

**Comment by huaiyumi** [comment]
The PTN ids can be linked to the pantree website, e.g., http://pantree.org/node/annotationNode.jsp?id=PTN000684825. However, it is true that it is not easy to trace the experimental evidence used to annotate the ancestor node.
