### ISSUE TITLE
The PANTHER PAINT FTP site no longer has /downloads/paint/ 

### ISSUE THREAD

**Issue by kltm** [geneontology/paint#52]
As part of the pipeline, locations such as ftp://ftp.pantherdb.org/downloads/paint/presubmission/gene_association.paint_tair.gaf.gz (as defined in the GO YAML metadata in go-site/metadata/datasets/paint.yaml) no longer seems to be defined. In fact, ftp://ftp.pantherdb.org/downloads/ no longer has a paint/ directory.

Has there been a change in the status of this location. This was first noticed at 12am last night and has continued to at least 4:30pm PDT.

Tagging @cmungall @huaiyumi

**Comment by kltm** [comment]
We also know that is still existed yesterday at 12am when the pipeline ran. This narrows the elimination to a 24 hour period.

**Comment by mugitty** [comment]
It has been moved to ftp://ftp.pantherdb.org/paint/.  If you already have scripts, I can move it back.  Let me know

**Comment by kltm** [comment]
Thank you! Currently, as you are the upstream for the metadata in the GO (https://github.com/geneontology/go-site/blob/master/metadata/datasets/paint.yaml), you probably want to update your metadata to the correct locations before make changes to the URL structure. For us, either returning to the old location or taking a PR to your metadata would be the easiest solutions.

**Comment by mugitty** [comment]
I have moved back to tp://ftp.pantherdb.org/downloads directory

**Comment by kltm** [comment]
Great, thank you!
