### ISSUE TITLE
Problem opening and curating large families with v1.14 of paint

### ISSUE THREAD

**Issue by huaiyumi** [geneontology/paint#7]
PAINT stops loading the tree after the "Initializing multiple sequence alignment" message shows up. The java console has the following message: 
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space

The family contains about 1800 sequences, however, the size of the family doesn't seem to be a problem, because PAINT has no problem opening a larger family (PTHR24361), which has over 2000 sequences.

**Comment by huaiyumi** [comment]
Actually this issue is probably related to the size of the family.  I was able to opened PTHR24093, which has about 1550 sequences, but a lot of experimental annotations in the matrix. After I propagated 2 terms, the software stop responding. There is the same message in the java console.

**Comment by selewis** [comment]
PTHR24093 and PTHR10489 both load fine in v2-beta. Also stay responsive.

Next time include any console output and record exactly what annotations you made so the error can be precisely replicated
