### ISSUE TITLE
Transfer of annotation using "contributes_to" in paint

### ISSUE THREAD

**Issue by ValWood** [geneontology/paint#9]
I wasn't sure which tracker this should go on (annotation or PAINT)

I suspect both, annotations need fixing, and annotation transfer policy needs reviewing

See detailed example in
https://github.com/geneontology/go-annotation/issues/1319

**Comment by selewis** [comment]
See wrap-up in geneontology/go-annotation#1319
golr loading wasn't including the qualifiers
should be rectified in next run of Touchup
